### ISSUE TITLE
Finalize configuration options

### ISSUE THREAD

**Issue by benatwork99** [smart-facility/cognicity-reports-detik#1]
I'm thinking the main processing for this could be driven by options like this:
- service URL (i.e., the URL including the topic ID)
- poll interval (i.e., how often to check for new items)
- historical load period (i.e., how far back do we go through items)

Internally, we can keep a record of the last 'contribution ID' processed to prevent processing old items again.

We can use the same 'cache while DB unavailable' behaviour that we have in the Powertrack data source.

Does this sound OK to you guys?

**Comment by matthewberryman** [comment]
Sounds good to me.

**Comment by benatwork99** [comment]
Resolved
