### ISSUE TITLE
JSHint tests broken in versions on JSHint > 2.5.8

### ISSUE THREAD

**Issue by tomasholderness** [smart-facility/cognicity-reports-detik#2]
- conflict between 'use strict' and global strict config in .jshintrc
- jshint -W020 inline fialing to stop Read Only errors.

See commit: https://github.com/smart-facility/cognicity-reports-detik/commit/52e5a0b4109633c9d5567da0bf1abac39edf9734 (roll back JSHint)
See Travis builds: https://travis-ci.org/smart-facility/cognicity-reports-detik/builds/90866093 (working), https://travis-ci.org/smart-facility/cognicity-reports-detik/builds/90865348 (broken)

**Comment by matthewberryman** [comment]
Presumable jshint's behaviour was changed for a reason, so we should really try and adopt new practice rather than roll back to an older version.

**Comment by benatwork99** [comment]
Linked:
https://github.com/smart-facility/cognicity-reports/issues/4
https://github.com/smart-facility/cognicity-server/issues/25
https://github.com/smart-facility/cognicity-reports-powertrack/issues/13
